#!/usr/bin/env bash
# Create a GitHub Project (v2) for this repo and seed it with issues/tasks, then add items to the project.
# Requires: gh CLI authenticated (gh auth login) with permission to create projects and issues.
# Usage: tools/create_github_project.sh "Project Name" "project-body"

set -euo pipefail
ROOT=$(git rev-parse --show-toplevel)
cd "$ROOT"

PROJECT_NAME="${1:-Repository Security Roadmap}"
PROJECT_BODY="${2:-Project generated by automation script. Review and edit columns as needed.}"

# find repo slug
REPO_FULL=$(git remote get-url origin 2>/dev/null || true)
if [[ -z "$REPO_FULL" ]]; then
  echo "Cannot determine repository remote URL (origin). Ensure origin exists and points to GitHub." >&2
  exit 1
fi
# normalize owner/repo
if [[ "$REPO_FULL" =~ github.com[:/]+([^/]+/[^/]+)(\.git)?$ ]]; then
  REPO_SLUG="${BASH_REMATCH[1]}"
else
  echo "Cannot parse GitHub repo slug from '$REPO_FULL'" >&2
  exit 1
fi

echo "Repo: $REPO_SLUG"

# Check if project already exists
EXISTING=$(gh project list --repo "$REPO_SLUG" --limit 100 | awk -F"\t" '{print $1}' | grep -xF "$PROJECT_NAME" || true)
if [[ -n "$EXISTING" ]]; then
  echo "Project '$PROJECT_NAME' already exists. Skipping creation.";
  # get project id
  PROJ_ID=$(gh project list --repo "$REPO_SLUG" --limit 100 --json number,name | jq -r ".[] | select(.name==\"$PROJECT_NAME\") | .number")
else
  echo "Creating project '$PROJECT_NAME'..."
  PROJ_ID=$(gh project create --repo "$REPO_SLUG" --name "$PROJECT_NAME" --body "$PROJECT_BODY" --json number --jq .number)
  echo "Created project number: $PROJ_ID"
fi

# Define tasks to create as issues (title|body)
read -r -d '' TASKS <<'EOF' || true
Rotate secrets and remove in-repo secrets
Ensure ADMIN_TOKEN, SECRET_KEY and any cookie tokens are rotated and stored in external secrets manager.

Run destructive history purge only after rotation.
--
Harden session cookies and enable HSTS in production
Verify SESSION_COOKIE_SECURE, HTTPONLY, SAMESITE and HSTS headers are enforced.
--
Implement mTLS between nginx and app
Add certificate distribution plan and update nginx/gunicorn configs to require client certs.
--
Apply deny-by-default WAF with staging tuning
Enable stricter WAF rules behind an env toggle; tune using red-team probes.
--
Enable non-root containers and read-only root fs
Update Dockerfiles to run as non-root, drop caps, and mount writable volumes only where required.
EOF

# Create issues and add to project
echo "Creating issues and adding them to project $PROJ_ID..."

while IFS= read -r title; do
  # skip empty lines
  if [[ -z "$title" ]]; then
    # consume blank separator
    read -r body || true
    continue
  fi
  read -r body || true
  echo "Creating issue: $title"
  ISSUE_URL=$(gh issue create --repo "$REPO_SLUG" --title "$title" --body "$body" --json number --jq .number)
  echo "Created issue #$ISSUE_URL"
  # add issue to project
  gh project item add --repo "$REPO_SLUG" --project "$PROJ_ID" --issue "$ISSUE_URL" || echo "Failed to add issue #$ISSUE_URL to project"
  # consume separator if present
  read -r sep || true
done < <(echo "$TASKS" | awk 'BEGIN{RS="\n--\n"} {print}' )

echo "Done. Open the project at: https://github.com/${REPO_SLUG}/projects/${PROJ_ID}"
