#!/usr/bin/env bash
# Create a GitHub Project (v2) for this repo and seed it with issues/tasks, then add items to the project.
# Requires: gh CLI authenticated (gh auth login) with permission to create projects and issues.
# Usage: tools/create_github_project.sh "Project Name" "project-body"

set -euo pipefail
ROOT=$(git rev-parse --show-toplevel)
cd "$ROOT"

PROJECT_NAME="${1:-Repository Security Roadmap}"
PROJECT_BODY="${2:-Project generated by automation script. Review and edit columns as needed.}"
# optional: labels and assignee from env
EXTRA_LABELS="${3:-security,infrastructure}"
EXTRA_ASSIGNEE="${4:-}"
USE_TEMPLATE="${5:-0}"

# find repo slug
REPO_FULL=$(git remote get-url origin 2>/dev/null || true)
if [[ -z "$REPO_FULL" ]]; then
  echo "Cannot determine repository remote URL (origin). Ensure origin exists and points to GitHub." >&2
  exit 1
fi
# normalize owner/repo
if [[ "$REPO_FULL" =~ github.com[:/]+([^/]+/[^/]+)(\.git)?$ ]]; then
  REPO_SLUG="${BASH_REMATCH[1]}"
else
  echo "Cannot parse GitHub repo slug from '$REPO_FULL'" >&2
  exit 1
fi

log_info "Repo determined" repo "$REPO_SLUG"

# Ensure required CLI tools are available
if ! command -v gh >/dev/null 2>&1; then
  echo "gh CLI not found. Install GitHub CLI: https://cli.github.com/" >&2
  exit 1
fi
if ! command -v jq >/dev/null 2>&1; then
  echo "jq not found. Install jq (e.g. apt install jq, brew install jq, or choco install jq)" >&2
  exit 1
fi

# Ensure gh is authenticated
if ! gh auth status >/dev/null 2>&1; then
  echo "gh is not authenticated. Run: gh auth login" >&2
  exit 1
fi

# helper: run a gh api call with retries for transient errors
gh_api_retry() {
  local method="$1"; shift
  local endpoint="$1"; shift
  local -i attempts=0
  local -i max=3
  local sleep_for=2
  while true; do
    attempts+=1
    if gh api --silent ${method:+--method $method} "$endpoint" "$@"; then
      return 0
    else
      echo "gh api ${method:-GET} $endpoint failed (attempt $attempts)" >&2
      if (( attempts >= max )); then
        echo "gh api failed after $attempts attempts" >&2
        return 1
      fi
      sleep $sleep_for
      sleep_for=$((sleep_for * 2))
    fi
  done
}

# helper: safe jq read that returns non-zero on parse errors
jq_read() {
  local expr="$1"; shift
  local file="$1"; shift
  local out
  if ! out=$(jq -r --exit-status "$expr" "$file" 2>&1); then
    echo "Failed to parse JSON ($file) with expression '$expr':" >&2
    echo "$out" >&2
    return 1
  fi
  printf "%s" "$out"
}

# Structured JSON log helpers (json-lines). Outputs to stdout so CI can parse.
# Usage: log_info "message" key1 val1 key2 val2 ...
log_json() {
  local level="$1"; shift
  local msg="$1"; shift
  # build meta object from remaining key/value pairs
  local -a kv=()
  while [[ $# -gt 1 ]]; do
    local k="$1"; local v="$2"; shift 2
    kv+=("\"$k\": \"$(python - <<PY
import json,sys
print(json.dumps(sys.argv[1]))
PY
" "$v")")
  done
  # assemble JSON safely via python
  python - <<PY
import json,sys,datetime
msg = sys.argv[1]
level = sys.argv[2]
meta_kvs = sys.argv[3:]
meta = {}
for kv in meta_kvs:
    try:
        k,v = kv.split('=',1)
        meta[k]=v
    except Exception:
        pass
record = {
    'ts': datetime.datetime.utcnow().isoformat() + 'Z',
    'level': level,
    'msg': msg,
    'meta': meta
}
print(json.dumps(record, ensure_ascii=False))
PY
}

log_info() { log_json info "$@"; }
log_warn() { log_json warn "$@"; }
log_error() { log_json error "$@"; }

# Check if project already exists
EXISTING=$(gh project list --repo "$REPO_SLUG" --limit 100 | awk -F"\t" '{print $1}' | grep -xF "$PROJECT_NAME" || true)
if [[ -n "$EXISTING" ]]; then
  log_info "Project exists; skipping creation" project "$PROJECT_NAME"
  PROJ_ID=$(gh project list --repo "$REPO_SLUG" --limit 100 --json number,name | jq -r ".[] | select(.name==\"$PROJECT_NAME\") | .number")
else
  log_info "Creating project" project "$PROJECT_NAME"
  if ! PROJ_ID=$(gh project create --repo "$REPO_SLUG" --name "$PROJECT_NAME" --body "$PROJECT_BODY" --json number --jq .number 2>&1); then
    log_error "Failed to create project" error "$PROJ_ID"
    exit 1
  fi
  log_info "Created project" project_id "$PROJ_ID"
fi

# Define tasks to create as issues (title|body)
TASKS=(
  "Rotate secrets and remove in-repo secrets|Ensure ADMIN_TOKEN, SECRET_KEY and any cookie tokens are rotated and stored in external secrets manager.\n\nRun destructive history purge only after rotation."
  "Harden session cookies and enable HSTS in production|Verify SESSION_COOKIE_SECURE, HTTPONLY, SAMESITE and HSTS headers are enforced."
  "Implement mTLS between nginx and app|Add certificate distribution plan and update nginx/gunicorn configs to require client certs."
  "Apply deny-by-default WAF with staging tuning|Enable stricter WAF rules behind an env toggle; tune using red-team probes."
  "Enable non-root containers and read-only root fs|Update Dockerfiles to run as non-root, drop caps, and mount writable volumes only where required."
)

IFS=',' read -r -a LABELS <<< "$EXTRA_LABELS"
if [[ -n "$EXTRA_ASSIGNEE" ]]; then
  ASSIGNEE="$EXTRA_ASSIGNEE"
else
  ASSIGNEE="$(echo "$REPO_SLUG" | cut -d'/' -f1)"
fi

echo "Creating issues and adding them to project $PROJ_ID..."

TEMPLATE_FILE=".github/project_template.json"
# If requested, read columns from project template file. Otherwise, fall back to defaults.
if [[ "${USE_TEMPLATE:-0}" == "1" ]]; then
  if [[ -f "$TEMPLATE_FILE" ]]; then
    log_info "Using project template" template "$TEMPLATE_FILE"
    # override project body/name if provided by template (but keep CLI overrides)
    tmpl_body=$(jq_read '.body // empty' "$TEMPLATE_FILE" ) || tmpl_body=""
    tmpl_name=$(jq_read '.name // empty' "$TEMPLATE_FILE" ) || tmpl_name=""
    if [[ -n "$tmpl_body" && -z "${2:-}" ]]; then
      PROJECT_BODY="$tmpl_body"
      log_info "Template provided project body; using template body"
    fi
    if [[ -n "$tmpl_name" && -z "${1:-}" ]]; then
      PROJECT_NAME="$tmpl_name"
      log_info "Template provided project name; using template name" project_name "$PROJECT_NAME"
    fi
    # read columns safely
    if ! mapfile -t TEMPLATE_COLUMNS < <(jq_read '.columns[]' "$TEMPLATE_FILE" ); then
      echo "Failed to read columns from template; aborting." >&2
      exit 1
    fi
    if [[ ${#TEMPLATE_COLUMNS[@]} -eq 0 ]]; then
      log_warn "Template contains no columns; falling back to defaults." reason "empty_columns"
      TEMPLATE_COLUMNS=("Backlog" "To Do" "In Progress" "Done")
    fi
  else
    echo "Template file not found: $TEMPLATE_FILE" >&2
    exit 1
  fi
else
  TEMPLATE_COLUMNS=("Backlog" "To Do" "In Progress" "Done")
fi

for col in "${TEMPLATE_COLUMNS[@]}"; do
  # check if column exists
  if ! cols_json=$(gh api --silent "/projects/${PROJ_ID}/columns" 2>&1); then
    echo "Failed to query project columns for project ${PROJ_ID}: $cols_json" >&2
    exit 1
  fi
  exists=$(printf "%s" "$cols_json" | jq -r --arg name "$col" '.[] | select(.name==$name) | .id' || true)
  if [[ -z "$exists" ]]; then
    log_info "Creating column" column "$col"
    if ! gh_api_retry POST "/projects/${PROJ_ID}/columns" -f name="$col" >/dev/null 2>&1; then
      log_error "Failed to create column after retries" column "$col"
    fi
  else
    log_info "Column exists" column "$col"
  fi
done

for item in "${TASKS[@]}"; do
  title="$(echo "$item" | cut -d'|' -f1)"
  body="$(echo "$item" | cut -d'|' -f2- )"
  log_info "Processing task" task "$title"
  # check if an issue with the same title already exists
  existing=$(gh issue list --repo "$REPO_SLUG" --limit 200 --json number,title | jq -r --arg t "$title" '.[] | select(.title==$t) | .number')
  if [[ -n "$existing" ]]; then
  log_info "Issue already exists" issue_number "$existing" title "$title"
    ISSUE_NUMBER="$existing"
  else
    # create new issue with labels and assignee
    label_args=()
    for l in "${LABELS[@]}"; do
      label_args+=(--label "$l")
    done
  log_info "Creating issue" title "$title"
    ISSUE_NUMBER=$(gh issue create --repo "$REPO_SLUG" --title "$title" --body "$body" "${label_args[@]}" --assignee "$ASSIGNEE" --json number --jq .number)
  log_info "Created issue" issue_number "$ISSUE_NUMBER"
  fi

  # ensure issue is added to project (avoid duplicate cards)
  # fetch issue URL
  issue_api_url="https://api.github.com/repos/${REPO_SLUG}/issues/${ISSUE_NUMBER}"
  duplicate=false
  # fetch columns list with retry
  if ! cols_json=$(gh api --silent "/projects/${PROJ_ID}/columns" 2>&1); then
    echo "Failed to list project columns for ${PROJ_ID}: $cols_json" >&2
    exit 1
  fi
  for col_id in $(printf "%s" "$cols_json" | jq -r '.[].id'); do
    if ! cards_json=$(gh api --silent "/projects/columns/${col_id}/cards" 2>&1); then
      echo "Warning: failed to fetch cards for column ${col_id}: $cards_json" >&2
      continue
    fi
    cards=$(printf "%s" "$cards_json" | jq -r --arg url "$issue_api_url" '.[] | select(.content_url==$url) | .id') || cards=""
    if [[ -n "$cards" ]]; then
      duplicate=true
      break
    fi
  done
  if [[ "$duplicate" == "true" ]]; then
    log_info "Issue already in project" issue_number "$ISSUE_NUMBER" project "$PROJ_ID"
  else
    # Add the issue to the specified column if mapping exists, otherwise default.
    COL_NAME=${COLUMN_MAP[$title]:-"Backlog"}
    # find column id
    COL_ID=$(printf "%s" "$cols_json" | jq -r --arg name "$COL_NAME" '.[] | select(.name==$name) | .id') || COL_ID=""
    if [[ -n "$COL_ID" ]]; then
      if ! gh_api_retry POST "/projects/columns/${COL_ID}/cards" -f content_id="$ISSUE_NUMBER" -f content_type="Issue" >/dev/null 2>&1; then
        log_error "Failed to add issue to column" issue_number "$ISSUE_NUMBER" column "$COL_NAME" column_id "$COL_ID"
      else
        log_info "Added issue to column" issue_number "$ISSUE_NUMBER" column "$COL_NAME"
      fi
    else
      log_warn "Column not found; using fallback add" column "$COL_NAME" issue_number "$ISSUE_NUMBER"
      if ! gh project item add --repo "$REPO_SLUG" --project "$PROJ_ID" --issue "$ISSUE_NUMBER" >/dev/null 2>&1; then
        log_error "Failed to add issue to project via fallback" issue_number "$ISSUE_NUMBER"
      else
        log_info "Added issue to project via fallback" issue_number "$ISSUE_NUMBER" project "$PROJ_ID"
      fi
    fi
  fi
done

log_info "All tasks processed" project "$PROJ_ID"
log_info "Done" url "https://github.com/${REPO_SLUG}/projects/${PROJ_ID}"
