#!/usr/bin/env bash
# Create a GitHub Project (v2) for this repo and seed it with issues/tasks, then add items to the project.
# Requires: gh CLI authenticated (gh auth login) with permission to create projects and issues.
# Usage: tools/create_github_project.sh "Project Name" "project-body"

set -euo pipefail
ROOT=$(git rev-parse --show-toplevel)
cd "$ROOT"

PROJECT_NAME="${1:-Repository Security Roadmap}"
PROJECT_BODY="${2:-Project generated by automation script. Review and edit columns as needed.}"

# find repo slug
REPO_FULL=$(git remote get-url origin 2>/dev/null || true)
if [[ -z "$REPO_FULL" ]]; then
  echo "Cannot determine repository remote URL (origin). Ensure origin exists and points to GitHub." >&2
  exit 1
fi
# normalize owner/repo
if [[ "$REPO_FULL" =~ github.com[:/]+([^/]+/[^/]+)(\.git)?$ ]]; then
  REPO_SLUG="${BASH_REMATCH[1]}"
else
  echo "Cannot parse GitHub repo slug from '$REPO_FULL'" >&2
  exit 1
fi

echo "Repo: $REPO_SLUG"

# Ensure required CLI tools are available
if ! command -v gh >/dev/null 2>&1; then
  echo "gh CLI not found. Install GitHub CLI: https://cli.github.com/" >&2
  exit 1
fi
if ! command -v jq >/dev/null 2>&1; then
  echo "jq not found. Install jq (e.g. apt install jq, brew install jq, or choco install jq)" >&2
  exit 1
fi

# Ensure gh is authenticated
if ! gh auth status >/dev/null 2>&1; then
  echo "gh is not authenticated. Run: gh auth login" >&2
  exit 1
fi

# Check if project already exists
EXISTING=$(gh project list --repo "$REPO_SLUG" --limit 100 | awk -F"\t" '{print $1}' | grep -xF "$PROJECT_NAME" || true)
if [[ -n "$EXISTING" ]]; then
  echo "Project '$PROJECT_NAME' already exists. Skipping creation.";
  # get project id
  PROJ_ID=$(gh project list --repo "$REPO_SLUG" --limit 100 --json number,name | jq -r ".[] | select(.name==\"$PROJECT_NAME\") | .number")
else
  echo "Creating project '$PROJECT_NAME'..."
  PROJ_ID=$(gh project create --repo "$REPO_SLUG" --name "$PROJECT_NAME" --body "$PROJECT_BODY" --json number --jq .number)
  echo "Created project number: $PROJ_ID"
fi

# Define tasks to create as issues (title|body)
TASKS=(
  "Rotate secrets and remove in-repo secrets|Ensure ADMIN_TOKEN, SECRET_KEY and any cookie tokens are rotated and stored in external secrets manager.\n\nRun destructive history purge only after rotation."
  "Harden session cookies and enable HSTS in production|Verify SESSION_COOKIE_SECURE, HTTPONLY, SAMESITE and HSTS headers are enforced."
  "Implement mTLS between nginx and app|Add certificate distribution plan and update nginx/gunicorn configs to require client certs."
  "Apply deny-by-default WAF with staging tuning|Enable stricter WAF rules behind an env toggle; tune using red-team probes."
  "Enable non-root containers and read-only root fs|Update Dockerfiles to run as non-root, drop caps, and mount writable volumes only where required."
)

LABELS=(security infrastructure)
ASSIGNEE="$(echo "$REPO_SLUG" | cut -d'/' -f1)"

echo "Creating issues and adding them to project $PROJ_ID..."

# create template columns if missing (classic project columns)
TEMPLATE_COLUMNS=("Backlog" "To Do" "In Progress" "Done")
for col in "${TEMPLATE_COLUMNS[@]}"; do
  # check if column exists
  exists=$(gh api --silent "/projects/${PROJ_ID}/columns" | jq -r --arg name "$col" '.[] | select(.name==$name) | .id' || true)
  if [[ -z "$exists" ]]; then
    echo "Creating column: $col"
    gh api --silent --method POST "/projects/${PROJ_ID}/columns" -f name="$col" >/dev/null || echo "Failed to create column $col"
  else
    echo "Column exists: $col"
  fi
done

for item in "${TASKS[@]}"; do
  title="$(echo "$item" | cut -d'|' -f1)"
  body="$(echo "$item" | cut -d'|' -f2- )"
  echo "Processing task: $title"
  # check if an issue with the same title already exists
  existing=$(gh issue list --repo "$REPO_SLUG" --limit 200 --json number,title | jq -r --arg t "$title" '.[] | select(.title==$t) | .number')
  if [[ -n "$existing" ]]; then
    echo "Issue already exists: #$existing - $title"
    ISSUE_NUMBER="$existing"
  else
    # create new issue with labels and assignee
    label_args=()
    for l in "${LABELS[@]}"; do
      label_args+=(--label "$l")
    done
    echo "Creating issue: $title"
    ISSUE_NUMBER=$(gh issue create --repo "$REPO_SLUG" --title "$title" --body "$body" "${label_args[@]}" --assignee "$ASSIGNEE" --json number --jq .number)
    echo "Created issue #$ISSUE_NUMBER"
  fi

  # ensure issue is added to project (avoid duplicate cards)
  # fetch issue URL
  issue_api_url="https://api.github.com/repos/${REPO_SLUG}/issues/${ISSUE_NUMBER}"
  duplicate=false
  for col_id in $(gh api --silent "/projects/${PROJ_ID}/columns" | jq -r '.[].id'); do
    cards=$(gh api --silent "/projects/columns/${col_id}/cards" | jq -r --arg url "$issue_api_url" '.[] | select(.content_url==$url) | .id')
    if [[ -n "$cards" ]]; then
      duplicate=true
      break
    fi
  done
  if [[ "$duplicate" == "true" ]]; then
    echo "Issue #$ISSUE_NUMBER already in project $PROJ_ID"
  else
    gh project item add --repo "$REPO_SLUG" --project "$PROJ_ID" --issue "$ISSUE_NUMBER" || echo "Failed to add issue #$ISSUE_NUMBER to project"
  fi
done

echo "Done. Open the project at: https://github.com/${REPO_SLUG}/projects/${PROJ_ID}"
